stages:
- build
- deploy
- clean

build:
  stage: build
  tags:
    - xlab
  script:
    - docker build -t $IMAGE .

deploy:
  stage: deploy
  tags:
    - xlab
  script:
    - docker login $LOGIN_INFO
    - docker push $IMAGE
    # - kubectl apply -f .k8s-resources/
  only:
    - prod

clean:
  stage: clean
  tags:
    - xlab
  script:
    - docker rmi $IMAGE